{% set version = "3.31.2" %}

package:
  name: cmake
  version: {{ version }}

source:
  - url: https://github.com/Kitware/CMake/releases/download/v{{ version }}/cmake-{{ version }}.tar.gz
    sha256: 42abb3f48f37dbd739cdfeb19d3712db0c5935ed5c2aef6c340f9ae9114238a2
  - url: https://cmake.org/files/v{{ version[:4] }}/cmake-{{ version }}-windows-x86_64.zip  # [win64]
    sha256: 109c29a744d648863d3637b4963c90088045c8d92799c68c9b9d8713407776c8  # [win64]
    folder: cmake-bin  # [win]
build:
  number: 0
  ignore_run_exports:
    - vc

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake-no-system  # [unix]

  host:
    - bzip2
    - libcurl         # [unix]
    - expat           # [unix]
    - ncurses         # [unix]
    - xz
    - zlib {{ zlib }}
    - libuv
    - rhash           # [unix]
    - zstd {{ zstd }}

  run:
    - bzip2
    - libcurl         # [unix]
    - expat           # [unix]
    - ncurses         # [unix]
    - xz
    - zlib
    - libuv
    - rhash           # [unix]
    - zstd
    - vs2015_runtime  # [win]
test:
  files:
    - SSLTest.cmake
  commands:
    - cmake --version
    - cmake -V -P SSLTest.cmake
    - ctest --version
    - cpack --version
    - ccmake --version  # [unix]

about:
  home: https://cmake.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - Copyright.txt
    - Utilities/cmbzip2/LICENSE         # [win]
    - Utilities/cmcurl/COPYING          # [win]
    - Utilities/cmexpat/COPYING         # [win]
    - Utilities/cmliblzma/COPYING       # [win]
    - Utilities/cmzlib/Copyright.txt    # [win]
    - Utilities/cmlibuv/LICENSE         # [win]
    - Utilities/cmlibrhash/COPYING      # [win]
    - Utilities/cmlibarchive/COPYING
    - Utilities/cmjsoncpp/LICENSE
  summary: CMake is an extensible, open-source system that manages the build process
  description: |
    CMake is a cross-platform, open-source build system generator.
  dev_url: https://gitlab.kitware.com/cmake/cmake
  doc_url: https://cmake.org/documentation/

extra:
  recipe-maintainers:
    - blowekamp
    - groutr
    - jakirkham
    - jschueller
    - ocefpaf
    - msarahan
    - scopatz
    - tadeu
    - marcelotrevisani
    - mingwandroid
