{% set version = "3.22.2" %}

package:
  name: cmake
  version: {{ version }}

source:
  - url: https://gitlab.kitware.com/cmake/cmake/-/archive/v{{ version }}/cmake-v{{ version }}.tar.bz2
    sha256: 3830b0247269bcc9db247e845e2da687d5b1844a93c12a9922ea637f168e0484
    folder: cmake
  - url: https://cmake.org/files/v{{ version[:4] }}/cmake-{{ version }}-windows-i386.zip  # [win32]
    sha256: 3830b0247269bcc9db247e845e2da687d5b1844a93c12a9922ea637f168e0484  # [win32]
  - url: https://cmake.org/files/v{{ version[:4] }}/cmake-{{ version }}-windows-x86_64.zip  # [win64]
    sha256: 3830b0247269bcc9db247e845e2da687d5b1844a93c12a9922ea637f168e0484  # [win64]
    folder: cmake-bin  # [win]

build:
  number: 0
  skip: True  # [win and vc<14]
  detect_binary_files_with_prefix: False
  ignore_run_exports:
    - vc

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make            # [unix]
    - m2-gcc-libs     # [win]
    - jom             # [win]
  host:
    - libcurl         # [unix]
    - expat           # [unix]
    - ncurses         # [unix]
    - rhash           # [unix]
    - bzip2
    - xz
    - zlib
    - zstd
    - libuv

test:
  files:
    - SSLTest.cmake
  commands:
    - cmake --version
    - cmake -V -P SSLTest.cmake
    - ctest --version
    - cpack --version
    - ccmake --version  # [unix]

about:
  home: https://cmake.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - cmake/Copyright.txt
    - cmake/Utilities/cmbzip2/LICENSE         # [win]
    - cmake/Utilities/cmcurl/COPYING          # [win]
    - cmake/Utilities/cmexpat/COPYING         # [win]
    - cmake/Utilities/cmliblzma/COPYING       # [win]
    - cmake/Utilities/cmzlib/Copyright.txt    # [win]
    - cmake/Utilities/cmlibuv/LICENSE         # [win]
    - cmake/Utilities/cmlibrhash/COPYING      # [win]
    - cmake/Utilities/cmlibarchive/COPYING
    - cmake/Utilities/cmjsoncpp/LICENSE
  summary: CMake is an extensible, open-source system that manages the build process
  dev_url: https://gitlab.kitware.com/cmake/cmake
  doc_url: https://cmake.org/documentation/

extra:
  recipe-maintainers:
    - blowekamp
    - groutr
    - jakirkham
    - jschueller
    - ocefpaf
    - msarahan
    - scopatz
    - tadeu
    - marcelotrevisani
    - mingwandroid
