{% set version = "3.11.1" %}
{% set major_minor = '.'.join(version.split(".")[:2]) %}

package:
  name: cmake
  version: {{ version }}

source:
  url: https://cmake.org/files/v{{ major_minor }}/cmake-{{ version }}.tar.gz
  fn: cmake-{{ version }}.tar.gz
  sha256: 57bebc6ca4d1d42c6385249d148d9216087e0fda57a47dc5c858790a70217d0c

  url: https://cmake.org/files/v{{ major_minor }}/cmake-{{ version }}.tar.gz              # [not win]
  fn: cmake-{{ version }}.tar.gz                                                          # [not win]
  sha256: b5d86f12ae0072db520fdbdad67405f799eb728b610ed66043c20a92b4906ca1                # [not win]

  url: https://cmake.org/files/v{{ major_minor }}/cmake-{{ version }}-win32-x86.zip       # [win32]
  fn: cmake-{{ version }}-win32-x86.zip                                                   # [win32]
  sha256: 8214df1ff51f9a6a1f0e27f9bd18f402b1749c5b645fbf6e401bcb00047171cd                # [win32]

  url: https://cmake.org/files/v{{ major_minor }}/cmake-{{ version }}-win64-x64.zip       # [win64]
  fn: cmake-{{ version }}-win64-x64.zip                                                   # [win64]
  sha256: 63b74a0685b2dd1c5d76428fd915539db6353dd8804aed5683a533ee1a08196d                # [win64]

build:
  number: 0
  skip: True   # [vc<14]

requirements:
  build:
    - {{ compiler('c') }}    # [unix]
    - {{ compiler('cxx') }}  # [unix]
  host:
    - bzip2                # [unix]
    - xz                   # [unix]
    - zlib                 # [unix]
    - expat                # [unix]
    - curl                 # [unix]
    - ncurses              # [unix]
    - libuv                # [unix]
    - rhash                # [unix]

test:
  files:
    - SSLTest.cmake
  commands:
    - cmake --version
    - cmake -V -P SSLTest.cmake
    - ctest --version
    - cpack --version

about:
  home: http://www.cmake.org/
  license: BSD 3-clause
  license_family: BSD
  summary: CMake is an extensible, open-source system that manages the build process
  description: |
    CMake is an open-source, cross-platform family of tools designed to build,
    test and package software.
  dev_url: https://gitlab.kitware.com/cmake/cmake/
  doc_url: https://cmake.org/documentation/
  doc_source_url: https://github.com/Kitware/CMake/blob/master/README.rst

extra:
  recipe-maintainers:
    - blowekamp
    - groutr
    - jakirkham
    - jschueller
    - ocefpaf
    - msarahan
    - scopatz
    - tadeu
