{% set version = "3.11.1" %}
{% set major_minor = '.'.join(version.split(".")[:2]) %}

package:
  name: cmake
  version: {{ version }}

source:
  url: https://cmake.org/files/v{{ major_minor }}/cmake-{{ version }}.tar.gz
  fn: cmake-{{ version }}.tar.gz
  sha256: 57bebc6ca4d1d42c6385249d148d9216087e0fda57a47dc5c858790a70217d0c

  url: https://cmake.org/files/v{{ major_minor }}/cmake-{{ version }}-win64-x64.zip       # [win64]
  fn: cmake-{{ version }}-win64-x64.zip                                                   # [win64]
  sha256: 86c0fde11caf22be08ee34971d49c91dbb1ef6315b2448f6725e9a05b753d251                # [win64]

build:
  number: 0
  detect_binary_files_with_prefix: true

requirements:
  build:                   # [unix]
    - {{ compiler('c') }}  # [unix]
  host:
    - bzip2                # [unix]
    - xz                   # [unix]
    - zlib                 # [unix]
    - expat                # [unix]
    - curl                 # [unix]
    - ncurses 6.*          # [unix]
    - libuv                # [unix]
    - rhash                # [unix]

  run:
    - curl            # [unix]
    - expat           # [unix]
    - ncurses 6.*     # [unix]
    - libuv           # [unix]
    - rhash           # [unix]
    - vs2013_runtime  # [win]

test:
  files:
    - SSLTest.cmake
  commands:
    - cmake --version
    - cmake -V -P SSLTest.cmake
    - ctest --version
    - cpack --version

about:
  home: http://www.cmake.org/
  license: BSD 3-clause
  license_family: BSD
  summary: CMake is an extensible, open-source system that manages the build process

extra:
  recipe-maintainers:
    - blowekamp
    - groutr
    - jakirkham
    - jschueller
    - ocefpaf
    - msarahan
    - scopatz
    - tadeu
