{% set name = "cmake" %}
{% set version = "4.1.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/Kitware/CMake/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.gz
    sha256: 643f04182b7ba323ab31f526f785134fb79cba3188a852206ef0473fee282a15
  - url: https://github.com/Kitware/CMake/releases/download/v{{ version }}/{{ name }}-{{ version }}-windows-x86_64.zip  # [win]
    sha256: 82730741149681597510a4bc7095da1460b472dac24eaf9c23ad7440f47753ab  # [win]
    folder: cmake-bin  # [win]

build:
  number: 0
  ignore_run_exports:
    - vc

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake-no-system  # [unix]
    - ninja-base
  host:
    - bzip2 {{ bzip2 }}
    - libcurl {{ libcurl }}  # [unix]
    - expat {{ expat }}  # [unix]
    - ncurses {{ ncurses }}  # [unix]
    - xz {{ xz }}
    - zlib {{ zlib }}
    - libuv {{ libuv }}
    - rhash  # [unix]
    - zstd {{ zstd }}
  run:
    - bzip2
    - libcurl         # [unix]
    - expat           # [unix]
    - ncurses         # [unix]
    - xz
    - zlib
    - libuv
    - rhash           # [unix]
    - zstd
    - vs2015_runtime  # [win]

test:
  files:
    - SSLTest.cmake
  commands:
    - cmake --version
    - cmake -V -P SSLTest.cmake
    - ctest --version
    - cpack --version
    - ccmake --version  # [unix]

about:
  home: https://cmake.org
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - cmake-bin/doc/cmake/cmcppdap/NOTICE  # [win]
    - cmake-bin/doc/cmake/cmcurl/COPYING  # [win]
    - cmake-bin/doc/cmake/cmlibarchive/COPYING  # [win]
    - cmake-bin/doc/cmake/cmliblzma/COPYING  # [win]
    - cmake-bin/doc/cmake/cmlibrhash/COPYING  # [win]
    - cmake-bin/doc/cmake/cmlibuv/LICENSE  # [win]
    - cmake-bin/doc/cmake/cmnghttp2/COPYING  # [win]
    - cmake-bin/doc/cmake/cmsys/Copyright.txt  # [win]
    - cmake-bin/doc/cmake/cmzlib/Copyright.txt  # [win]
    - cmake-bin/doc/cmake/cmzstd/LICENSE  # [win]
    - LICENSE.rst
    - Licenses/LGPLv2.1.txt
    - Licenses/LGPLv3.txt
  summary: CMake is an extensible, open-source system that manages the build process
  description: |
    CMake is a cross-platform, open-source build system generator.
  dev_url: https://gitlab.kitware.com/cmake/cmake
  doc_url: https://cmake.org/documentation

extra:
  recipe-maintainers:
    - blowekamp
    - groutr
    - jakirkham
    - jschueller
    - ocefpaf
    - msarahan
    - scopatz
    - tadeu
    - marcelotrevisani
    - mingwandroid
