{% set version = "3.11.1" %}
{% set major_minor = '.'.join(version.split(".")[:2]) %}

package:
  name: cmake
  version: {{ version }}

source:
  url: https://cmake.org/files/v{{ major_minor }}/cmake-{{ version }}.tar.gz              # [not win]
  sha256: 57bebc6ca4d1d42c6385249d148d9216087e0fda57a47dc5c858790a70217d0c                # [not win]

  url: https://cmake.org/files/v{{ major_minor }}/cmake-{{ version }}-win32-x86.zip       # [win32]
  sha256: 415a24c0c1250514747ea3c1d45b1930bc51dc5d6acb01062e1d680051bb0ea9                # [win32]

  url: https://cmake.org/files/v{{ major_minor }}/cmake-{{ version }}-win64-x64.zip       # [win64]
  sha256: ed23c3d22e164fae7300c82db3e72eac4648e016eabdeace1bd573a9a6ecd218                # [win64]

build:
  number: 0
  skip: True   # [vc<14]

requirements:
  build:
    - {{ compiler('c') }}    # [unix]
    - {{ compiler('cxx') }}  # [unix]
  host:
    - bzip2                  # [unix]
    - expat                  # [unix]
    - libuv                  # [unix]
    - libcurl                # [unix]
    - ncurses                # [unix]
    - rhash                  # [unix]
    - xz                     # [unix]
    - zlib                   # [unix]

test:
  files:
    - SSLTest.cmake
  commands:
    - cmake --version
    - cmake -V -P SSLTest.cmake
    - ctest --version
    - cpack --version

about:
  home: http://www.cmake.org/
  license: BSD 3-clause
  license_family: BSD
  summary: CMake is an extensible, open-source system that manages the build process
  description: |
    CMake is an open-source, cross-platform family of tools designed to build,
    test and package software.
  dev_url: https://gitlab.kitware.com/cmake/cmake/
  doc_url: https://cmake.org/documentation/
  doc_source_url: https://github.com/Kitware/CMake/blob/master/README.rst

extra:
  recipe-maintainers:
    - blowekamp
    - groutr
    - jakirkham
    - jschueller
    - ocefpaf
    - msarahan
    - scopatz
    - tadeu
