{% set name = "cmake" %}
{% set version = "4.3.4" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/Kitware/CMake/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.gz
    sha256: fdeff897b9eb49d764539f2b1edc6eb7e1440df325678a97c1978499e931adda
  - url: https://github.com/Kitware/CMake/releases/download/v{{ version }}/{{ name }}-{{ version }}-windows-x86_64.zip  # [win and x86_64]
    sha256: 86e5fcafb38bdf58346a78b187c7b6b4f252ae5242cffe24c463a92bbd2e77d1
    folder: cmake-bin  # [win and x86_64]
  - url: https://github.com/Kitware/CMake/releases/download/v{{ version }}/{{ name }}-{{ version }}-windows-arm64.zip  # [win and arm64]
    sha256: 91a59ca6ffbcec18e1fb05431fa22f538ab615b6e525d1bfd0b8dd67a4d45685
    folder: cmake-bin  # [win and arm64]

build:
  number: 0
  ignore_run_exports:
    - vc

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake-no-system  # [unix]
    - ninja-base
  host:
    - bzip2 {{ bzip2 }}
    - libcurl {{ libcurl }}  # [unix]
    - expat {{ expat }}  # [unix]
    - ncurses {{ ncurses }}  # [unix]
    - xz {{ xz }}
    - zlib {{ zlib }}
    - libuv {{ libuv }}
    - rhash  {{ rhash }}  # [unix]
    - zstd {{ zstd }}
  run:
    - bzip2
    - libcurl  # [unix]
    - expat  # [unix]
    - ncurses  # [unix]
    - xz
    - zlib
    - libuv
    - rhash  # [unix]
    - zstd

test:
  files:
    - SSLTest.cmake
  commands:
    - cmake --version
    - cmake -V -P SSLTest.cmake
    - ctest --version
    - cpack --version
    - ccmake --version  # [unix]

about:
  home: https://cmake.org
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - cmake-bin/doc/cmake/cmcppdap/NOTICE  # [win]
    - cmake-bin/doc/cmake/cmcurl/COPYING  # [win]
    - cmake-bin/doc/cmake/cmlibarchive/COPYING  # [win]
    - cmake-bin/doc/cmake/cmliblzma/COPYING  # [win]
    - cmake-bin/doc/cmake/cmlibrhash/COPYING  # [win]
    - cmake-bin/doc/cmake/cmlibuv/LICENSE  # [win]
    - cmake-bin/doc/cmake/cmnghttp2/COPYING  # [win]
    - cmake-bin/doc/cmake/cmsys/Copyright.txt  # [win]
    - cmake-bin/doc/cmake/cmzlib/Copyright.txt  # [win]
    - cmake-bin/doc/cmake/cmzstd/LICENSE  # [win]
    - LICENSE.rst
    - Licenses/LGPLv2.1.txt
    - Licenses/LGPLv3.txt
  summary: CMake is an extensible, open-source system that manages the build process
  description: |
    CMake is a cross-platform, open-source build system generator.
  dev_url: https://gitlab.kitware.com/cmake/cmake
  doc_url: https://cmake.org/documentation

extra:
  recipe-maintainers:
    - blowekamp
    - groutr
    - jakirkham
    - jschueller
    - ocefpaf
    - msarahan
    - scopatz
    - tadeu
    - marcelotrevisani
    - mingwandroid
