travis:
  secure:
    BINSTAR_TOKEN: fR5bW4/lXsc0fD7thCZ0sZIbvo5oEl8JriS98c9K++87rlncwSdwVvCECDJt1nd1wjzzYVp3XqBz/XudvFrKfJ9GeYN8vEV1Cgq9mgh3RedGKl+yLchlbuvK3zURlk92LV5bIuANA5psozrP+zCsGgepc8eLndw7i2YrNiFrUHDzKHVaUzo/wWUJip39l0kXpP1sLy0auow2L944a5N/6l0OciOcEPm7tz10VKjnG2Gr6iD3T5o6x0WJG4FH1eSqwiUT3WScZLN13Gqnm3HKPEzMGeDmQrmN4/CsSp5pBYriuMALgMz4xWTftPe0kbBDnlzKw1rrYJf+MkZhKeBFjjWTQNF4jHZ+h1GNJL3W5w1ivs+ueJ6QW2fRFgvByEzNVqYkWliC02WnFpuwNJojUK0R1V9ENwzTYoDK0WJmTlZTiGc+Pma514hTsE/6EEsj06OLgizKZeRrlfI2TzFS6PrLhWd9koE47EEF1ADpH5oyLIs9EKmLVKoTvm0qNywuQDh0oiKN3ra2C7Cmw/gUtWnQzaMLZaHICQGHPaGBoOi6phDyqW2qF+RiFTjCv+hErOHV8OMMc/TY0lEHnkXthK2PCxOXznsPJE8Wz14cb7B/ADnMb3NZclJ+a9l0ya6TYuXtJHx35EqrCUgJwYs7z79Qw3g0m0TxNUFCxTc2hlM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
