travis:
  secure:
    BINSTAR_TOKEN: ZqO06Najc0h1iMaw2FLuFE+4854oigqj1GD+d6UgRFMjm4niSAIiNZdzm1YXwf5O2iKvyPc8poB937ywt9vjLF0IniEXDeB5aYfGi/SP24mv5HWdvT5ikPLqnWI7KBDl5RkW484dAS8cSjeRzZvZEIMlUJ/JvTVKW289jOxrS5ySMMptWvNHR2PMjWgTFPVm+OHHfFbGFo+lHrxui6AYvVN26ke9YBOZpQOvLAJxJsXAGjqLYIj65dJiVXsWpi5ggexoDB/TF5iFYFmEfvJ6H5WiwwLiIZCei5GhK1zjAj6G70xTf8cKPGfsP1Nb2iYoQC9Oes1DwBNDYXZ8yXsYQPHZhW8kalxXgdbdDz6L6Oj11HXGmM4qqgRIi3lcQOk0ChdnESFTzCEgjsBsvFEXP+0+oIiu3pNRK5lM9myGQnz3MPynMMGxYFc/rL7KY/O8tWnfoKTSCw7pkVe1MiwQNz+WUEtUtEbeyQQ6vM8Sg11humALGV1hpWFEQFaPuB3Fishwy6R0XtzyS+lMZW6CSCLgZNoJppKeNj1fNJTwXi59GJt8es6mWijWspI8f9GUzvTSL7nq4yA7pP7U0n5YnVnU7j22whsekmnA/ryiYoSHRnbnho9tI5AxcA2Rt9e2EKfIKBU95GNXLXqOr4gxz/9x3cB8/N82kTFaxe+GAUs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
