travis:
  secure:
    BINSTAR_TOKEN: ecO+helHSGhMOzToL+adceeFt9MXNDrsZb3lUxojENjdzmMwzEGAN5NbOdD5RBceG4xwt5kiYJRKm5UAvwO3qP715aAVxCjgXk+6rFFsPZf3mBsrOG+m8SoF3Rllb35eJHXMYVlRxoyVXKoduUA6/W12WGLBWT4vw8AP0RafLXjAg1CFJcgcFQoZAAJNzfHwymD0s5npfeyLWXzd5aWgQFf6QF1gBnETrtngi9IHKc+uE0J3uWHBwFqwjLF4R3luPkMX/fysHydpBRSKZrLOIFbNc81+xXM78b5YMv0xwnkd+NdnbGH0dz3zMP23NER/id+99rzo6IiLbPEGLMADebeD2laCQ20hQWg40op1f6DhDq9QPpNhBEBgCnWkkgssvSaUyo2bDxcqWlGk+pdr3g+LTwPhiGfGRYD+pXOaJd5mDAM1TEoVAdG89vYIr4JIt+4lqdjLfImhILgGOqyUFsMInr7HEBab1766kAf1RnuAk8Xp4iUzN/Un6BREwqXGamuAo4cF68cQw6XMp0plC7gQ+bCD1/LcrnljBR8YfYJhSGlOhVYmhwSsOszvpNj0OB9Xc7YKEsdWRlULoMbxSBGtJFEQ4AgUWDjTXkQECLLCcRAvSRca/Fcr0RN+QrdyrlfA5ZE061VdvZLzu5m/QaMYLHMvG/nQPWA74otgTic=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
