travis:
  secure:
    BINSTAR_TOKEN: fbPLEci495U+fxji2/d2hOjzCfZ09sopTQJ4npTmGjBKZxqeuWSCYdBjS9RVNNblWlOJcxZhe1T75UD/I15r+aXqEAnYxVa12mTw9K+o9eV0JGmDhwGTTPoUNVF2jCiTt/L3xOF0OpQHBERJ6Xhe3su66X9S3d8R4WWePxg11ew3ZG/hr3je8hDnffLirW/L8OI8Pb4KdFjLVigejN7Vy4aqVTlJ4rvksAvNFjsxj0AiicNl05+QssY3pMFK8TWlkcqbJ9gRR4plJrztbwZAj1W22HolXEUVJvxyq6xZSXTQdyBf4S5YyKjhHxI4/P7xFak7rQP7mohPzUis7AnTUKosANn0iUZkqJaks099wvAKFLbLZrZsKEB5j33PsHH8KMGg+dTrReptFJqF9W4wDAcN3CQ8L6CYI0v0hWLQgD19ypyyFu8L6oo9R9yuoZMJUh2NNNpJVyZahz2Y+LffiDqZWPsgrYWKZ4CwJGUJ0W5/waniGBAqmQ+bV/oI4RMhO+wGkUxrJjHWWIJaA8k8Pvi8ACgxU/coEc6CQAHlqvmetMvjJNmKlJwh1AuGRe4pIKBC0Vid70xtiGHxwWwWFa4GDfzsUFzmo6VzJP3Mi0ZPf384yKqBQtPLU+BRX+bQkHMifz/hP33XWrlno7U8WUk3P96qGqopucupaMsbFKM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
